services:
##  service-pg:
##    image: bitnami/postgresql:latest
##    ports:
##      - '5432:5432'
##    environment:
##      - POSTGRESQL_USERNAME=docker
##      - POSTGRESQL_PASSWORD=docker
##      - POSTGRESQL_DATABASE=carnahall

  service-redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
