POST http://localhost:3333/inscricoes
Content-Type: application/json 
// determina o formato que os dados serão enviados

{
    "nome": "Neemias Cormino",
    "email": "ncormino@gmail.com"
}

// nova rota
###

GET http://localhost:3333/convites/neemias